### ISSUE TITLE
make plugin asynchronous

### ISSUE THREAD

**Issue by dsavchenko** [oda-hub/dispatcher-plugin-gw#1]
I have no experience with it. @volodymyrss or @burnout87 I will need your consultation

**Comment by volodymyrss** [comment]
Let us discuss on Monday, and then maybe schedule an extra meeting. Or I make a tutorial of a kind, next week.
But in short, try this async endpoint. Or maybe wait until I show.

**Comment by volodymyrss** [comment]
could you refer me to a notebook so I can make an example?

**Comment by dsavchenko** [comment]
Current head of the plugin is here https://github.com/oda-hub/dispatcher-plugin-gw/tree/image
The backend is here https://github.com/oda-hub/gw-seed-backend/tree/skymap
And the modified frontend is here https://github.com/dsavchenko/frontend-astrooda/tree/gw

**Comment by volodymyrss** [comment]
Could you please make PRs? to reduce possible confusion about what is needed to be done, and follow [the process](https://github.com/oda-hub/doc-handbook).

**Comment by dsavchenko** [comment]
I've not created any PR because these branches aren't really finished. Improvements should be made; api=True parts should be implemented in the plugin. But I want to incorporate the feedback from GW people firstly.

**Comment by volodymyrss** [comment]
> I've not created any PR because these branches aren't really finished. Improvements should be made; api=True parts should be implemented in the plugin. But I want to incorporate the feedback from GW people firstly.

you can make draft PR. Also you can avoid requesting review. In both cases there will be no review and merging will not be expected any time soon.
If there is a PR, it can be assigned to milestone, etc. Since milestone has been decided, we can do it.

**Comment by dsavchenko** [comment]
I am trying to implement (semi?)async for gw (without deploying async dispatcher with celery) but I am stuck 

In the plugin, I call the async backend endpoint and obtain the state. Then it can be processed like here https://github.com/oda-hub/dispatcher-plugin-gw/blob/810ef26b2961111112550681f0c5b7b8a9e79e8e/dispatcher_plugin_gw/dataserver_dispatcher.py#L108
But as far as request is not *query_status=new* the plugin is not called, instead execution goes here https://github.com/oda-hub/dispatcher-app/blob/c41607ce9a4570404298cc3b2cdf5570b3720a4d/cdci_data_analysis/flask_app/dispatcher_query.py#L1748 
and the returned status is always 'submitted'.

Where should I look?

**Comment by volodymyrss** [comment]
I do not know if the non-callback version of async still works, I will need to have a look. https://github.com/oda-hub/dispatcher-app/issues/293

But, there might be an easier option, to make nb2service return a call-back https://github.com/volodymyrss/nb2workflow/issues/19 
.

**Comment by volodymyrss** [comment]
from nb2workflow>=1.3.9 it will send callbacks if requested, just like the dda (integral) backend.

see example in there https://github.com/oda-hub/gw-seed-backend/blob/async-callbacks/example-async.sh#L36

It should work pretty much exactly like integral plugin. Please consult in there. Please ask if unclear.
